### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by SamuelAvb** [cdimascio/nationalparks_conversation#11]
TypeError: Cannot read property 'url' of undefined
    at createRequest (C:\example_1\nationalparks_conversation\node_modules\watson-developer-cloud\lib\requestwrapper.js:168:45)
    at ConversationV1.message (C:\example_1\nationalparks_conversation\node_modules\watson-developer-cloud\conversation\v1.js:221:10)
    at createCbObservable (C:\example_1\nationalparks_conversation\node_modules\rx\dist\rx.async.js:268:6)
    at C:\example_1\nationalparks_conversation\node_modules\rx\dist\rx.async.js:308:12
    at Conversation.message (C:/example_1/nationalparks_conversation/server/api/services/conversation.js:21:12)
    at DiscourseService.message (C:/example_1/nationalparks_conversation/server/api/services/discourse/index.js:10:8)
    at Controller.messages (C:/example_1/nationalparks_conversation/server/api/controllers/conversation/controller.js:7:8)
    at Layer.handle [as handle_request] (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\route.js:112:3)
TypeError: Cannot read property 'url' of undefined
    at createRequest (C:\example_1\nationalparks_conversation\node_modules\watson-developer-cloud\lib\requestwrapper.js:168:45)
    at ConversationV1.message (C:\example_1\nationalparks_conversation\node_modules\watson-developer-cloud\conversation\v1.js:221:10)
    at createCbObservable (C:\example_1\nationalparks_conversation\node_modules\rx\dist\rx.async.js:268:6)
    at C:\example_1\nationalparks_conversation\node_modules\rx\dist\rx.async.js:308:12
    at Conversation.message (C:/example_1/nationalparks_conversation/server/api/services/conversation.js:21:12)
    at DiscourseService.message (C:/example_1/nationalparks_conversation/server/api/services/discourse/index.js:10:8)
    at Controller.messages (C:/example_1/nationalparks_conversation/server/api/controllers/conversation/controller.js:7:8)
    at Layer.handle [as handle_request] (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\route.js:112:3)
TypeError: Cannot read property 'url' of undefined

**Comment by SamuelAvb** [comment]
> TypeError: Cannot read property 'url' of undefined
> at createRequest (C:\example_1\nationalparks_conversation\node_modules\watson-developer-cloud\lib\requestwrapper.js:168:45)
> at ConversationV1.message (C:\example_1\nationalparks_conversation\node_modules\watson-developer-cloud\conversation\v1.js:221:10)
> at createCbObservable (C:\example_1\nationalparks_conversation\node_modules\rx\dist\rx.async.js:268:6)
> at C:\example_1\nationalparks_conversation\node_modules\rx\dist\rx.async.js:308:12
> at Conversation.message (C:/example_1/nationalparks_conversation/server/api/services/conversation.js:21:12)
> at DiscourseService.message (C:/example_1/nationalparks_conversation/server/api/services/discourse/index.js:10:8)
> at Controller.messages (C:/example_1/nationalparks_conversation/server/api/controllers/conversation/controller.js:7:8)
> at Layer.handle [as handle_request] (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\layer.js:95:5)
> at next (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\route.js:137:13)
> at Route.dispatch (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\route.js:112:3)
> TypeError: Cannot read property 'url' of undefined
> at createRequest (C:\example_1\nationalparks_conversation\node_modules\watson-developer-cloud\lib\requestwrapper.js:168:45)
> at ConversationV1.message (C:\example_1\nationalparks_conversation\node_modules\watson-developer-cloud\conversation\v1.js:221:10)
> at createCbObservable (C:\example_1\nationalparks_conversation\node_modules\rx\dist\rx.async.js:268:6)
> at C:\example_1\nationalparks_conversation\node_modules\rx\dist\rx.async.js:308:12
> at Conversation.message (C:/example_1/nationalparks_conversation/server/api/services/conversation.js:21:12)
> at DiscourseService.message (C:/example_1/nationalparks_conversation/server/api/services/discourse/index.js:10:8)
> at Controller.messages (C:/example_1/nationalparks_conversation/server/api/controllers/conversation/controller.js:7:8)
> at Layer.handle [as handle_request] (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\layer.js:95:5)
> at next (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\route.js:137:13)
> at Route.dispatch (C:\example_1\nationalparks_conversation\node_modules\express\lib\router\route.js:112:3)
> TypeError: Cannot read property 'url' of undefined
